### ISSUE TITLE
feat: Absolute Path

### ISSUE THREAD

**Issue by pruthvi145** [luanpotter/vscode-dart-import#41] opened 2021-09-25 04:45 UTC
Some developers (like me) prefer to add an absolute path instead of a relative path.

Is something similar available for us fellows?

**Comment by luanpotter** [comment] 2021-10-20 00:07
Closing as duplicate of https://github.com/bluefireteam/vscode-dart-import/issues/39

**Closed as completed by luanpotter** 2021-10-20 00:07 UTC
